### ISSUE TITLE
开启 `at` 选项后，bot不再响应其他中间件的内容

### ISSUE THREAD

**Issue by Logthm** [Kokoro-js/koishi-plugin-why-not-ask-ai#1]
## 问题

开启 `at` 选项后，bot不再响应其他中间件的内容。

应该是检测 @ 消息的中间件未在结束时调用 next() 函数。

## 环境

```
System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz

Binaries:
    Node: 20.12.2
    Yarn: 4.1.1

Koishi:
    Core: 4.17.9
    Console: 5.29.2
    Koishi Desktop: 1.1.3
```

## 建议

处理非 @ 消息时，直接调用 next() 函数；

处理 @ 消息时，若没有匹配到指令，则调用 next() 函数。

**Comment by itzdrli** [comment]
https://github.com/Kokoro-js/koishi-plugin-why-not-ask-ai/commit/fdba006077e983fbfcc5fd7558d2661776242525

试试 0.0.6

**Comment by Logthm** [comment]
> [fdba006](https://github.com/Kokoro-js/koishi-plugin-why-not-ask-ai/commit/fdba006077e983fbfcc5fd7558d2661776242525)
> 
> 试试 0.0.6

测了下还是不太行，我提 PR 了。

**Comment by itzdrli** [comment]
好的，感谢
